
{{ if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cla-tls
  namespace: default
spec:
  secretName: cla-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ .Values.claAssistant.host | default "cla.w3f.tech" }}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - {{ .Values.claAssistant.host | default "cla.w3f.tech" }}
{{ end }}
