apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "cla.fullname" . }}-mongodb-credentials'
  labels:
    name: 'mongodb-credentials'
data:
  uri: {{ .Values.claAssistant.uri  | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "cla.fullname" . }}-github-credentials'
  labels:
    name: 'github-credentials'
data:
  client: {{ .Values.github.client | default  "GITHUB_CLIENT" | b64enc }}
  secret: {{ .Values.github.secret | default  "GITHUB_SECRET" | b64enc }}
  user: {{ .Values.github.user | default  "GITHUB_USER" | b64enc }}
  token: {{ .Values.github.token | default  "GITHUB_TOKEN" | b64enc }}
  admins: {{ .Values.github.admins | default  "GITHUB_ADMIN" | b64enc }}
