apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "cla.fullname" . }}-mongodb-credentials'
  labels:
    name: 'mongodb-credentials'
data:
  uri: {{ .Values.claAssistant.uri  | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "cla.fullname" . }}-github-credentials'
  labels:
    name: 'github-credentials'
data:
  secret: {{ .Values.github.secret | default  "GITHUB_SECRET" | b64enc }}
  pass: {{ .Values.github.password | default  "GITHUB_PASSWORD" | b64enc }}
  token: {{ .Values.github.token | default  "GITHUB_TOKEN" | b64enc }}
