# Default values for cla-assistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
domain: cla.w3f.tech
environment: production

image:
  repository: web3f
  tag: 0.0.1
  pullPolicy: IfNotPresent

production:
  enabled: true

claAssistant:
  host: cla.w3f.tech
  port: 5000
  uri: mongodb://username:password@cla-mongodb/db

github:
  client:
  user:
  secret:
  password:
  token:

mongodb:
  mongodbRootPassword:
  service:
    port: 27017

  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: 4.0.14-debian-9-r0
    pullPolicy: IfNotPresent

    debug: false

  volumePermissions:
    enabled: false
    image:
      registry: docker.io
      repository: bitnami/minideb
      tag: stretch
      pullPolicy: Always
  usePassword: true
  mongodbEnableIPv6: false
  mongodbDirectoryPerDB: false

  mongodbSystemLogVerbosity: 0
  mongodbDisableSystemLog: false

  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  clusterDomain: cluster.local

  service:
    type: ClusterIP
    port: 27017
  replicaSet:
    enabled: false
    useHostnames: true
    name: rs0
    replicas:
      secondary: 1
      arbiter: 1
    pdb:
      enabled: true
      minAvailable:
        primary: 1
        secondary: 1
        arbiter: 1
  updateStrategy:
    type: RollingUpdate

  persistence:
    enabled: true
    mountPath: /bitnami/mongodb
    subPath: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  metrics:
    enabled: false

    image:
      registry: docker.io
      repository: bitnami/mongodb-exporter
      tag: 0.10.0-debian-9-r77
      pullPolicy: IfNotPresent
    livenessProbe:
      enabled: false
      initialDelaySeconds: 15
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: false
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1

    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9216"

    serviceMonitor:
      enabled: false

replicaCount: 1

serviceAccount:
  create: true

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
