# Default values for cla-assistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

claAssistant:
  host:
  port:
  hostPort:
  protocol:

github:
  secret: "a3da5d4a65ds"
  password: "a3da5d4a65ds"
  token: "a3da5d4a65ds"

mongodb:
  mongodbRootPassword: "23123132123231231"
  service:
    port: 56985
  mongodbUsername: mongol
  mongodbPassword: "password"
  mongodbDatabase: cla
  replicaSet:
    enabled: true
    replicas:
      secondary: 1
      arbiter: 1
    pdb:
      enabled: true
      minAvailable:
        secondary: 1
        arbiter: 1
      maxUnavailable:
        secondary: 1
        arbiter: 1

  resourcesArbiter:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

replicaCount: 2

prometheus-mongodb-exporter:
  mongodb:
    uri: "mongodb://mongol:password@mongo:56985/cla"

  resources:
   limits:
     cpu: 250m
     memory: 192Mi
   requests:
     cpu: 100m
     memory: 128Mi

   serviceMonitor:
     namespace: default

image:
  repository: web3f
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
