version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/cla-assistant .

  chartLint:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - run:
          description: create lint command
          command: |
CMD=$(cat <<-END
helm lint --set \
environment="ci",\
claAssistant.host=$CLA_ASSISTANT_HOST,\
claAssistant.protocol=$PROTOCOL,\
claAssistant.port=$PORT,\
claAssistant.hostPort=$HOST_PORT,\
github.secret=$GITHUB_SECRET,\
github.password=$GITHUB_PASSWORD,\
github.token=$GITHUB_TOKEN,\
mongodb.mongodbRootPassword=$MONGODB_ROOT_PASSWORD,\
mongodb.mongodbUsername=$MONGODB_USERNAME,\
mongodb.mongodbPassword=$MONGODB_PASSWORD,\
mongodb.mongodbDatabase=$MONGODB_DATABASE \
 ./charts/cla/.
END
)
      - run:
          description: helm lint
          command: |
            eval $CMD
      - run:
          description: create template command
          command: |
CMD=$(cat <<-END
helm template --set \
environment="ci",\
claAssistant.host=$CLA_ASSISTANT_HOST,\
claAssistant.protocol=$PROTOCOL,\
claAssistant.port=$PORT,\
claAssistant.hostPort=$HOST_PORT,\
github.secret=$GITHUB_SECRET,\
github.password=$GITHUB_PASSWORD,\
github.token=$GITHUB_TOKEN,\
mongodb.mongodbRootPassword=$MONGODB_ROOT_PASSWORD,\
mongodb.mongodbUsername=$MONGODB_USERNAME,\
mongodb.mongodbPassword=$MONGODB_PASSWORD,\
mongodb.mongodbDatabase=$MONGODB_DATABASE \
 ./charts/cla/.
END
)
      - run:
          description: helm template
          command: |
            eval $CMD

  integrationTests:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishImage:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/cla-assistant

  publishChart:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

  deploy:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - run:
          environment:
            GCP_REGION: europe-west3
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - buildImage:
          filters:
            tags:
              only: /.*/
      - chartLint:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage
            - chartLint
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishImage
            - publishChart
