version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: yarn lint

  buildImage:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: /scripts/build-image.sh web3f/cla-assistant .

  publishImage:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: /scripts/publish-image.sh web3f/cla-assistant

  testChart:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/cla-assistant/.
      - run:
          command: |
            helm install --dry-run --debug --generate-name ./charts/cla-assistant/.
      - run:
          command: |
            helm install budapest-acipenser ./charts/cla-assistant/.
      - run:
          command: |
            helm test budapest-acipenser


  integrationTests:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout

  publishChart:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - run:
           command: |
             /scripts/publish-chart.sh
  deploy:
    docker:
      - image: web3f/ci-commons:v1.7.1
    steps:
      - checkout
      - run:
          environment:
            GCP_REGION: europe-west3
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - buildImage:
      - publishImage:
        requires:
          - buildImage
      - testChart:
        requires:
          - publishImage
      - integrationTests:
        requires:
          - testChart
      - publishChart:
        requires:
          - integrationTests
