apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cla-assistant.fullname" . }}
  labels:
    {{- include "cla-assistant.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cla-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cla-assistant.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cla-assistant.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: HOST
            value: {{ .Values.host }}
          - name: PORT
            value: {{ .Values.port | default 80 }}
          - name: HOST_PORT
            value: {{ .Values.hostPort | default 8080 }}
          - name: PROTOCOL
            value: {{ .Values.protocol | default "http" }}
          - name: GITHUB_CLIENT
            value: {{ .Values.githubClient | default "CLIENT" }}
          - name: GITHUB_SECRET
            valueFrom:
              secretKeyRef:
                name: github-credentials
                key: secret
          - name: GITHUB_USER
            value: "Hello from the environment"
          - name: GITHUB_PASS
            valueFrom:
              secretKeyRef:
                name: github-credentials
                key: pass
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-credentials
                key: token
          - name: GITHUB_ADMIN_USERS
            value: "Such a sweet sorrow"
          - name: MONGODB
            valueFrom:
              secretKeyRef:
                name: mongodb credentials
                key: uri
          ports:
            - name: http
              containerPort: {{ .Values.port | default 80 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
