apiVersion: apps/v1
kind: Deployment
metadata:
  name: cla-assistant
  namespace: {{ .Values.namespace }}
  labels:
    app: polkadot-watcher
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: cla-assistant
  template:
    metadata:
      labels:
        app: cla-assistant
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: pcla-assistant
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi
