apiVersion: v1
kind: Secret
metadata:
  name: github credentials
  namespace: {{ .Values.namespace }}
  labels:
    name: github credentials
  annotations:
    description: Github credentials
data:
  secret: {{ .Values.GITHUB_SECRET | default  "GITHUB_SECRET" | b64enc }}
  pass: {{ .Values.GITHUB_PASSWORD | default  "GITHUB_PASSWORD" | b64enc }}
  token: {{ .Values.GITHUB_TOKEN | default  "GITHUB_TOKEN" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb credentials
  namespace: {{ .Values.namespace }}
  labels:
    name: mongodb credentials
  annotations:
    description: MongoDB Credentials
data:
  uri: {{ .Values.MONGODB | default  "MONGODB mongodb://<user>:<password>@<host>:<port>/<dbname>" | b64enc }}
